#!/bin/bash
ALXroot@fd2fd96aa60:/alx-pre_course/0x01-git/bash# cat > school
#!/bin/bash
Schoolroot@fd2fd96aa60c:/alx-pre_course/0x01-git/bash# ls
alx school
root@fd2fd96aa60c:/alx-pre_course/0x01-git/bash# cat alx
#!/bin/bash
